name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

defaults:
    run:
        shell: bash
        working-directory: ./infra

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}  # GitHub SecretsにIAMロールを指定

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
